language: ruby
cache: bundler
rvm:
 - 2.3.3

before_script:
 - chmod +x ./script/build

script: ./script/build

branches:
  except:
  - master

branches:
  only:
  - docs

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
