# TEST RUN TCI SUPPORT
language: ruby

cache:
  yarn: true
  bundler: true
  directories:
    - node_modules

rvm:
 - 2.4

before_script:
 - chmod +x ./script/build

script: ./script/build

branches:
  except:
  - master

branches:
  only:
  - docs

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
