language: ruby

addons:
  ssh_known_hosts: github.com

cache:
  yarn: true
  directories:
    - node_modules

rvm:
 - 3.0.0

before_install:
 - nvm install 10.13.0 

before_script:
 - chmod +x ./script/build

script: ./script/build

branches:
  except:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: docs
